### ISSUE TITLE
Missing tested-with field in .cabal file

### ISSUE THREAD

**Issue by asr** [pachopepe/Calculational#1]

**Comment by pachopepe** [comment]
tested-with flag added to cabal file

**Comment by asr** [comment]
Thanks!

**Comment by pachopepe** [comment]
Gracias a ti Andrés

El 2 oct. 2016 20:10, "Andrés Sicard-Ramírez" notifications@github.com
escribió:

Thanks!

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
https://github.com/pachopepe/Calculational/issues/1#issuecomment-251009190,
or mute the thread
